version: '3'

services:
  db:
    image: postgres:14
    container_name: postgres
    ports:
      - 8888:5432
    volumes:
      - db-store:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      PGPASSWORD: postgres
      POSTGRES_DB: lalavel
      TZ: "Asia/Tokyo"
volumes:
  db-store: